### ISSUE TITLE
Ability to disable teams module - Very slow world loading.

### ISSUE THREAD

**Issue by brandyyn** [Unknown025/Flans-Mod-Plus#150]
Hi, in my pack, using flans(any version) world creation / load takes an extremely long time. I believe this is due to the teams module in flans as these errors are spammed continuously

![image](https://user-images.githubusercontent.com/11356565/209449475-dec49fd1-0bd5-47a7-afba-8422503b1e2a.png)

![image](https://user-images.githubusercontent.com/11356565/209449476-abba93fe-72f9-43e1-94cd-8673217b83b0.png)

![image](https://user-images.githubusercontent.com/11356565/209449493-5db36f0b-0802-4696-8cd3-15e98639f54a.png)

![image](https://user-images.githubusercontent.com/11356565/209449488-5f2c3094-2256-4229-9a7f-94f7ceab05a8.png)
(i removed machetemens pack and this particular one went away, but it's still a pack i'd like to play with and disabling teams module should remove this anyway, right?) 

![image](https://user-images.githubusercontent.com/11356565/209449508-6ced3de9-48ad-40ac-b129-f4a3c2772db4.png)

![image](https://user-images.githubusercontent.com/11356565/209449510-9dc679f6-f331-4c2e-ad2c-18c465edb172.png)
(this is taken from a version of my pack BEFORE adding this flans fork, but the log spam is from this current version)

**Comment by makamys** [comment]
To provide some more details, the teams module takes 4 minutes in total to load the world data on my machine in said modpack. (Using this fork this time.)
![](https://user-images.githubusercontent.com/13667520/209449604-ec7cec9f-ec01-435a-b744-0657b07145f0.png)
Deleting `teams_*.dat` in the world directory makes the world load much faster, confirming it's the root of the issue. Using `/teams off` doesn't fix the problem.

Since the module is a non-integral part of the mod, it would be nice if it could be disabled.

**Comment by GoldSloth** [comment]
Thanks for posting this issue, I'll try and explain what's going on here and how you might be able to fix the issue you're having.

Firstly: Teams isn't really an independent module, it contains a lot of other non-minigame stuff such as armour, in game configuration via /teams command and a few other things. FlansMod is a bit of a mess.

The console log errors are normal, they won't be slowing down your game loading much if at all. They're reporting errors with your content packs, not with the mod itself. You can hide them using options in FlansMod.cfg - you don't need to stop using the packs because of the errors.
They're unrelated to the teams stuff too, armour items were built into teams first and remain there.

So, onto the main issue: the loading time. That looks like `com.flansmod.common.teams.PlayerClass.onWorldLoad` is taking ages. I'd guess you've got lots of items loaded and it's struggling to search for items it needs to add. Lmk if that's the case.

Anyway, a player class is setup in the `teams` or `class` (I think? Might be wrong) folders in each content pack, and it sets up a loadout of items to be used in teams mini games. If you go through and delete those folders, it won't try and create the loadouts.

Let me know if that fixes the problem, and also if you're using many mods/packs - whether I need to go and look at optimising the player class stuff.

**Comment by brandyyn** [comment]
yeah, this is a pack with around 462 mods in it. 

currently it takes 2 minutes exactly in my pack to load back into a world. this is without the content pack that was giving the error in the screenshot below.

![image](https://user-images.githubusercontent.com/11356565/209454892-3a92f2bf-f1c6-4ab1-aacd-b453d916cd24.png)
this was the little error culprit

i've gone ahead and deleted all the classes and teams folders in all of my content packs and after deleting teams and classes folders in all my content mods, it now only takes 50 seconds to rejoin a world, this is also now with the content pack that WAS giving that error.

**Comment by GoldSloth** [comment]
50 seconds still seems like a long time, but with 462 mods I could believe it. I'm glad that's made it a bit better!

**Comment by brandyyn** [comment]
i believe it takes a while due to minecraft having to load every dimension on world load, weirdly. my pack has a lot of dimensions, but regardless of that- this is a huge improvement and i'm very happy. out of curiosity, if the player class was optimized would i see any benefit now that i've deleted these folders or is this that now void in my case?

**Comment by GoldSloth** [comment]
The optimisations wouldn't have any effect, probably.

It's a hypothetical because it's unlikely I'll get around to it.

**Comment by brandyyn** [comment]
i do think it's a good idea to fix as it's clearly quite an issue, especially one that isn't exactly "known" about, for a functionality most flans users dont even know exists.

**Comment by GoldSloth** [comment]
I haven't come across this one before so I doubt it's common - and it'll only happen with a lot of items in the game. I agree it'd be a good idea to optimize it.

The reason I'm unlikely to get to it is a lack of time, and the backlog for the mod is pretty huge:
https://trello.com/b/zMVdRWcz/flansmod-ultimate-stability-project

**Comment by brandyyn** [comment]
thank you so much for your help. my issue personally has been fixed, so atleast you can advise others to do the same. it might be good to note it somewhere, like a warning "Warning, in big modpacks this mod, flans substantially increases world loading times, click here for fix", something like that might be good :)

**Comment by GoldSloth** [comment]
Thanks for your input, I'll put a link to this issue on the curseforge page.

I'll close this for now, but lmk if there's anything else.

**Comment by xJon** [comment]
Also suffered from this issue, and simply by updating to this Flan's fork (using v1.56) it was completely resolved (presumably thanks to https://github.com/Unknown025/Flans-Mod-Plus/commit/794f26a41f42a7601b66ff07cb5d6f9570cabf1d). Thanks!
