### ISSUE TITLE
Sound upon vehicle hit

### ISSUE THREAD

**Issue by LavaHoleD** [Unknown025/Flans-Mod-Plus#166]
A new kind of sound: when a vehicle is hit, it will play a configurable sound/s defined in the vehicle config file and stored in the assets folder.

It could be done in three ways:
`1.` **The simplest one**: simply a new parameter which redirect to a sound.
`2.` **The intermediate one**: it will play an array of sounds (ex. `vehicleHitSound sfx1, sfx2, sfx3`).
`3.` **The hard one**: it will play a different sound depending on the damage value the vehicle has taken.

Edit: actually I just realized that there is a big difference between low caliber impact sounds and high caliber impact sounds. Perhaps it would have to be a bit more specific, maybe having a different sound based on the type of entity bullet that hit it.

Edit n2: yeah probably it would be a lot easier to add a parameter for ammo configs directly for vehicle hit sound.

It would be a small neat feature to improve realism

**Comment by GoldSloth** [comment]
There's already a hitmarker sound that plays for the shooter, but I agree a version that plays for the hit vehicle would make sense. It might be a bit tricky to get the config organised well, because of the different combinations of bullets and vehicles. Overall it's a low priority feature though so we're unlikely to get to it - I'll add it to the Trello board though.

Thanks for the suggestion:)

**Comment by LavaHoleD** [comment]
No problem and no worries! Keep up the good work!

**Comment by GoldSloth** [comment]
Tracked by https://github.com/Unknown025/Flans-Mod-Plus/issues/179

Please reopen or new issue if needed.
