### ISSUE TITLE
[Suggestion] Allow vehicle parameters to be modified

### ISSUE THREAD

**Issue by beeffeter456** [Unknown025/Flans-Mod-Plus#179]
The idea would be as follows: 

- You can modify the explosions size **_and_** the damage of the weapons on vehicles. It would be similar to how you can already modify the damage of guns with a modifier, but just for vehicles instead, or possibly for specific vehicle types, like planes or tanks only, etc. 

- A modifier could be added to change the velocity of shells or bullets.

- A modifier that changes vehicle health.

- Config option to allows tanks to vehicles to destroy certain blocks on contact, like wood, leaves, etc (also possibly allow you to change which blocks as well?)

**Comment by GoldSloth** [comment]
Would that be a global modifier set in flansmod.cfg?

**Comment by beeffeter456** [comment]
Yes, it would

**Comment by GoldSloth** [comment]
Okay, that shouldn't be too hard to implement. I'll add it to our feature tracker. Thanks :)

For the last two points, due to the way vehicle health works this isn't a great idea. It might be possible to put in specific damage modifiers for damage inflicted on vehicles though.

For the last point, this already exists in the harvester system. see https://github.com/Unknown025/Flans-Mod-Plus/wiki/Player-Collisions. Most vehicles don't have the right configs setup for this so having it as a global option isn't feasible. Prototype_Theta's British Military Pack has a few vehicles that use this feature iirc.

**Comment by beeffeter456** [comment]
I see, well thanks anyway, your work is greatly appreciated!

**Comment by GoldSloth** [comment]
Tracked by https://trello.com/c/I1WCXFGX
Reopen or new issue if needed.
