### ISSUE TITLE
Version 1.8?

### ISSUE THREAD

**Issue by oleg12054** [Unknown025/Flans-Mod-Plus#184]
Will you update the mod for 1.8 and newer versions of minecraft and how long will it take? I faced the problem of transferring the pack from 1.7.10 ultimatum flan to a regular flan 1.8. The item itself appears and the icon is present, and the skin or model or both cases will work for some reason. The screenshot shows the hitbox of the car, there is no car itself. Can I try to fix this display myself? It seems to me that I have tried and checked the correctness of the transfer 5 times, the pack should display all this, but I don't understand what it doesn't like.

![2023-07-05_10 12 14](https://github.com/Unknown025/Flans-Mod-Plus/assets/127609432/495dfb4b-3f3d-4d67-8e3d-d8e6c9010f86)

**Comment by GoldSloth** [comment]
There's no plans to update this mod past 1.7.10, our aim is to keep supporting the few people who still use 1.7.10.

Someone has been working on a port to 1.12 but it's pretty unstable and he's not worked on it for a while.

In terms of transferring a pack to a newer version, FM+ has a lot of features that regular Flans doesn't. I'd advise the easiest thing to do is find a config that works in 1.8 and try to get the model and texture into it then work backwards.

However it's possible the model won't work because it differences in the ModelVehicle class.

**Comment by oleg12054** [comment]
I see. I hope in the future you will still be able to support newer versions. Since 1.7.10 becomes obsolete and version 1.7.10 itself loses many of the features that are available from 1.8 and 1.8.9. And in 1.16.5 and higher, there are even more of them. I understand that modding on 1.7.10 is much simpler and unique in its own way and supports those functions that are not available in other versions and there are the same mods that have not been supported since then by orespawn, fiskheroes, arcania and others, but the new versions also support many additional functions that allow you to do much more advanced and unique content, I think that every year the prospects with the transition to a new version will only grow. It would be good if you added the version as it is purely so that there would be an opportunity at least to run such packages. I think this is a real idea

**Comment by GoldSloth** [comment]
I don't disagree with you that it's a good idea to have versions for newer Minecraft updates. But it's a lot of work and I'm not motivated to do that - anybody can make a fork of this update and port it to a later version of they'd like.
