### ISSUE TITLE
SetPlayerInvisible does not work on passengers

### ISSUE THREAD

**Issue by beeffeter456** [Unknown025/Flans-Mod-Plus#190]
Setting SetPlayerInvisible to true does not work on passengers. They remain visible. Items that are held by an invisible player are also not invisible.

fml-client-latest: https://mclo.gs/KWqLgEl

![2023-12-30_22 26 26](https://github.com/Unknown025/Flans-Mod-Plus/assets/66223689/a974c2d8-ad2a-42c8-b40c-3017f52ea49d)
![2023-12-30_22 26 49](https://github.com/Unknown025/Flans-Mod-Plus/assets/66223689/d58f277f-0a1f-4d7f-b8c3-a567d036a4dc)

[T0T Mark I.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/13800102/T0T.Mark.I.txt)

this was solved in the TaP version of Flans, although that was implemented as a per-passenger configuration as evident in the vehicle file

**Comment by GoldSloth** [comment]
Yup, passenger visibility has been requested a lot and never implemented. https://trello.com/c/4ERuU0IU

And items being visible I think is due to vanilla MC does visibility. Might be complicated to work around that.

As this mod isn't going to get feature updates anymore it's unlikely these are going to get fixed. Sorry about that .-.

**Comment by GoldSloth** [comment]
Now tracked by https://trello.com/c/4ERuU0IU/511-setplayerinvisible-for-passenger-seats
