### ISSUE TITLE
When aim anywhere, projectiles travel normally, but when aim at mobs, projectiles instant hit mobs

### ISSUE THREAD

**Issue by xdeadstokex** [Unknown025/Flans-Mod-Plus#191]
better example below

**Comment by GoldSloth** [comment]
Sorry I don't really understand what you mean - could you include a more description and a screen recording if possible?

**Comment by xdeadstokex** [comment]
better example below

**Comment by xdeadstokex** [comment]
> Sorry I don't really understand what you mean - could you include a more description and a screen recording if possible?

here:https://drive.google.com/file/d/1KNzPLB4po6waEv7TaeRIPWSAmbsOfc49/view?usp=sharing
as the video point out, the panzerfault rocket has a low speed, but when i aim it at the creeper, it instant hit that mob

**Comment by GoldSloth** [comment]
I'll test it out. I don't see a big difference between the two but I'll see if I can replicate something like that.

**Comment by xdeadstokex** [comment]
just set bullet speed by a low variable, you can feel it (I found this "maybe bug" bc it feel weird when the bullet teleport to mob)

**Comment by GoldSloth** [comment]
I haven't been able to replicate this - are you definitely using FM+USE 1.7.10? I think newer versions of Flansmod are using hitscan rather than projectile + raytracing like 1.7 does.

Otherwise the only explanation I can give is that the bullet may detonate sooner when hitting a mob than if it were hitting the ground, there is some degree of proximity but it wouldn't cause that much difference.

https://streamable.com/ogzo1h
https://streamable.com/mu7qag

If this is still an issue, could you provide more video examples showing the behavior? I don't see a big difference in the first one. But thank you for reporting it regardless :)

**Comment by xdeadstokex** [comment]
I found sth interesting:
turn out, it is not Flan bug (I use 1.7.10 btw), it is this mod which interacting with Flan mod hit scan or sth, without it, bullet fly normally
https://github.com/quentin452/OptimizationsAndTweaks-this mod is new, it fix bug and optimizing MC

sorry for the inconvenience and thank for your help, btw, can you give some advice or improvement, bc there is some vehicle models which is too laggy, and these thing are not fully entitys either, so other performance mods cant reduce the lag cause by them.

**Comment by GoldSloth** [comment]
I don't really understand how that could cause the issue we're seeing, but I'm glad we know the cause.

Vehicles lagging is usually caused by their texture size. It may be possible to downscale them but often not. FlansMod isn't very efficient at rendering them. There's not loads we can do about that easily sorry.
