### ISSUE TITLE
Getting kicked from server when killing other player

### ISSUE THREAD

**Issue by dieflemm** [Unknown025/Flans-Mod-Plus#22]
When shooting another player and killing him using weapons from Flans Mod, both players get kicked from the server. They can rejoin without their client crashing. Just an error message appears.

If I kill myself in singleplayer by using a grenade I get kicked out of my world, after restarting my client crashes. 
I am running this mod in a custom 1.7.10 modpack. Tried versions 1.43 and 1.44.

The crash report is from a singleplayer world where I killed myself with a grenade and tried to reopen my world, on my server theres no crash report.

[crash-2021-02-21_19.39.42-server.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/6018368/crash-2021-02-21_19.39.42-server.txt)

**Comment by GoldSloth** [comment]
I'll have a look into it. Could you send a latest.log from clients and server when you do it on a server, please?

**Comment by dieflemm** [comment]
Hey, here are the logs. I renamed them. I was using Version 1.44. It only happens when using weapons from flans.

[latest - client got killed.log](https://github.com/Unknown025/Flans-Mod-Plus/files/6021754/latest.-.client.got.killed.log)
[latest - client who killed.log](https://github.com/Unknown025/Flans-Mod-Plus/files/6021756/latest.-.client.who.killed.log)
[latest - server.log](https://github.com/Unknown025/Flans-Mod-Plus/files/6021757/latest.-.server.log)

**Comment by GoldSloth** [comment]
Hello, The issue is that one of your content packs has a bullet (could be a shell, ammunition e.t.c.) without a defined shortname. The shortname is the main piece of identifying information an item has, and is.. very much needed for the item to function properly.
To find which item is causing these issues, you can use a process of elimination of your packs. Once you know which pack it is, you can do a similar process of elimination with the files in the `bullets` folder. The offending suspect will be missing the line:
`ShortName <somethinghere>`

Once you find that file, you can add something like:
`ShortName naughtyitem`.

If you find out with pack is causing the issue, you can also tell the content pack maker, so they can fix it.

Hope that helps :)

**Comment by dieflemm** [comment]
it was indeed the content pack which caused the problem. tested your flan version with another content pack and it worked fine. I looked into the files and found the missing ShortName. Works fine now. thank you for your time and your help. :)
