### ISSUE TITLE
Vehicle Crash(FIXED)

### ISSUE THREAD

**Issue by Corgi119** [Unknown025/Flans-Mod-Plus#23]
Whenever I spawn a vehicle, My game crashes. I am on the proper version and everything else works fine.

Here is the message when I open the launcher
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Ticking entity
Exit Code: -1

Here is the full error report
https://pastebin.com/LMvKCmCa

**Comment by Unknown025** [comment]
I'll look into it, thanks for reporting this.

**Comment by GoldSloth** [comment]
Hello, I'm fairly sure this is because your vehicle doesn't have an engine set in it.
Are you spawning the vehicle in, if so how, (creative menu/ /give) or are you crafting it?
Also, do you have any packs installed with engines in them, like the simple parts pack or the SMP parts pack.

If you're spawning them in from creative without a pack installed with an engine, that may be the cause.

**Comment by Corgi119** [comment]
Oh! Fixed! You need an engine :)
Thanks!
