### ISSUE TITLE
Vehicle crash while using GUI

### ISSUE THREAD

**Issue by User4240** [Unknown025/Flans-Mod-Plus#30]
Hello, my game crashed while I was using the repair gui...

Here is the crash report:
https://pastebin.com/ep6eGTsT

**Comment by GoldSloth** [comment]
Thanks, I'll look into it.

**Comment by GoldSloth** [comment]
Hi, does this happen consistently when entering a vehicle? If so, a specific vehicle, when you first place it, all vehicles e.t.c.?
It looks like when the GUI is opened, the entity is null somehow. I've put in a small case that should detect this and close the GUI if that's the case. If this is a regular thing, we'll have to do more investigation and see what the cause is.

**Comment by User4240** [comment]
This happens when I have the GUI open and someone shoots me and I die, then my game crashes

**Comment by GoldSloth** [comment]
Ahh, that makes sense, thank you.

**Comment by GoldSloth** [comment]
It might be fixed, it's quite hard to test to get the right combination of things happening. Reopen this is if it happens again, please.
