### ISSUE TITLE
any chance of 1.12 version?

### ISSUE THREAD

**Issue by TRLWeiss** [Unknown025/Flans-Mod-Plus#4]
even though Flansmod Official has released a Flansmod in 1.12.2,but in fact,that version can not support any content pack in 1.7.10.
so could there be any chance to update your 1.7.10 flansmod to 1.12.2 so that it can support content pack in previous version?

**Comment by Unknown025** [comment]
This is a bit of a loaded question. Our fork of Flans Mod is meant to deliver the most stable possible experience for **1.7.10**. Content pack support likely differs between 1.12 and 1.7.10 mainly due to a lot of rendering changes in 1.12, so even if we updated our fork to 1.12, it wouldn't solve your problem. That being said, there are some FM+ changes that aren't available in the official fork of Flans Mod, which might be added eventually.
