### ISSUE TITLE
Problems with grenade model

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#46]
I'm currently trying to add a "C4-like" grenade to my game but unfortunately I have some problems with the model. I just can't wrap my head around how the grenade models work. The first major issue is that the disk-like shape at the bottom of the explosive doesn't seem to be in the right place for some reason and the second problem has something to do with the positioning of the model. So I was wondering how can I move the model (like "translateAll" on gun models) and secondly where the issue with the model itself might be that causes the bottom part of the model to be all glitched out?

Thanks for help ;)

My model file in eclipse:
[ModelConvertModem.txt](https://github.com/Unknown025/Flans-Mod-Plus/files/6866177/ModelConvertModem.txt)

This what the model is supposed to look like:
![Screenshot (212)](https://user-images.githubusercontent.com/76816145/126728244-3295da00-4c9d-4655-baf2-b40aeeeeb51b.png)

This is what it looks like ingame (note the hitbox that shows where the model would ideally be):
![2021-07-23_03 27 30](https://user-images.githubusercontent.com/76816145/126728246-31fd3597-920d-4d17-9fb1-6b4b7e97b985.png)
![2021-07-23_03 27 23](https://user-images.githubusercontent.com/76816145/126728255-2b04ed28-e946-4763-8755-01f480732f97.png)

**Comment by GoldSloth** [comment]
Heya, hope you're doing well.

I'll have to examine this more closely to see what's going on, my first thoughts though:

Make sure your model is built around the origin

And try switching to using offsets instead of positions. There is a button for this in TB iirc, that will switch them all around.

I'm not great on this side of the mod. There's a discord server called minecraft-smp.de where most of the modellers are, they'd hopefully be able to help you there. If you join the FM+USE discord, there should be a link in announcements, if not: DM me or Ping me and I'll post one.

Hope that's helps ;)

**Comment by pixelrider2000** [comment]
I'll fiddle around with it a bit more now and see if I can make some progress. May you send me a link to the discord server though? I'd appreciate it.

A little of topic: Since I'm using this version of flans mod, I was always wondering why vehicles (e.g. when driving off a cliff) teleport to  the ground instantly instead of falling slowly like in other versions of flans mod. What exactly is the reason for this change? 

Many thanks!

**Comment by GoldSloth** [comment]
There should be a link to the FM+USE discord on the front page, the readme of this repository.

As for falling vehicles: aye, I made that change because I got really pissed off by vehicles that just *softly glide down* at a constant speed. The system I put in instead uses acceleration, so the speed increases the further you fall (as is in the real world). My values may be a bit aggressive, I don't think I did much testing to decide what value to use. If you think it's too aggressive, I can look at changing it

**Comment by pixelrider2000** [comment]
Should I open a new issue on that vehicle topic? I would like to say some more  things about that ;)

**Comment by GoldSloth** [comment]
Sure, that'd be a good idea.

**Comment by pixelrider2000** [comment]
You were right, using the offset instead of positioning fixed it!
But I have one more question, is there a way how I can change the model scale (either in toolbox or in the config file of the grenade itself)?
![Screenshot (214)](https://user-images.githubusercontent.com/76816145/126787046-63ffca23-48f5-4af2-988a-baa5eeb0a01a.png)

**Comment by pixelrider2000** [comment]
Never mind, I got it now. Much thanks for the great help again though!
