### ISSUE TITLE
Future Feature Request: Vehicle HUDs, Radar, Weapon Selection

### ISSUE THREAD

**Issue by conman180** [Unknown025/Flans-Mod-Plus#54]
I Know it would be complicated to pull off properly, but I feel this could really enhance the gameplay of this mod. To have certain HUDs for different vehicle types as well as variations of them. For aircraft flying in first or third-person and tanks in first-person, it could be especially useful. 
For tanks it would allow
-A  Crosshair of a sort (think Battlefield 4)
-Detection of nearby mobs, players, and drivables (configurable as to which are enabled)
-Thermal/night vision (LabJac has done this with his TaP version)
-Visual Locking on of targets(HUD draws a box around what is configured to be detected)
For Aircraft it would allow
-Attitude indication
-Visual Locking on of targets (same as above)(Think Ace Combat Series)

As for weapon selection
I feel that rather than separate keybinds for Missiles, bombs, and guns, there shoul just be a
Fire Primary and Fire Secondary with another key to change what secondary is selected
The HUD Would display what weapon is selected along with how much ammo.

Sorry for long winded description but i like to pay attention to details.

**Comment by GoldSloth** [comment]
Thank you for the suggestions, I think the ammo indicator is a pretty good idea, as for the others - they're good but could be difficult to implement. I've already spoken to labjac about night vision, and he does it using one of the built in shaders. Drawing on screen around mobs is a whole different level of complexity. I'll write them all up into the list, but I can't promise any of these will get done because of the current backlog of other suggestions, and my lack of free time right now.

**Comment by conman180** [comment]
If this is any help when this can potentially be worked on, The drawing on screen around targets has already been done in a different mod. The RC Mod pulled it off quite well. However the source code isn't available. It draws a box around available targets and the circle inside shows which target is locked on to.
![2021-08-18_14 58 25](https://user-images.githubusercontent.com/78190656/129957083-4c03bd3c-62cb-41d8-924c-c9114c2182b5.png)
